### ISSUE TITLE
Broken loop in AccessLog::isIgnoredPath()

### ISSUE THREAD

**Issue by ghost** [jstnryan/slim-access-log#7]
Hi Justin,

The code of the method isIgnoredPath() in v1.1.2 does not loop over multiple ignore paths. 
It only handles the first value in the list.

A possible correction might be :
```
if( !!preg_match("@^{$ignore}(/.*)?$@", $uri)){
    return true;
}
```

Regards, Tom

**Comment by jstnryan** [comment]
A potentially disastrous oversight on my part. Thank you for the suggestion.

Fixed in Master: https://github.com/jstnryan/slim-access-log/blob/master/src/AccessLog.php#L146
